#!/bin/bash

FULLPATH=`cd $(dirname $0); pwd`
#echo $FULLPATH >&2
PROJECT=`echo $FULLPATH | awk -F/ '{print $(NF-3)}'`
STATUS=`echo $0 | awk -F- '{print $NF == "worked" ? "pass" : ($NF == "reset" ? "building" : "fail")}'`

SCRIPTS_PATH="$(dirname "$(readlink -f "$0")")"
ruby $SCRIPTS_PATH/update Project $PROJECT author:$AUTHOR status:$STATUS

